### ISSUE TITLE
Interactive result

### ISSUE THREAD

**Issue by ghost** [essanpupil/pygoogling#4]
I'm thinking about the result after we actually run the search and get the result, 
Don't want to be disturbing or rude, the result is actually **boring to read**
Why is it boring to read it? Because the data looks like a RESTful-API.

Can you actually style the result to actually be more interactive like down below(example):

<hr>

Title of the web: link of the web

```
Welcome to Python.org: https://www.python.org/
```

**Comment by essanpupil** [comment]
Actually, somebody already requesting this feature, https://github.com/essanpupil/pygoogling/issues/2
But unfortunately i'm still too busy working on my other opensource project. Don't worry, it is not rude to request new feature.

**Comment by ghost** [comment]
👍🏽
